version: 2
updates:
- package-ecosystem: maven
  directory: "/Android"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
